language: java
jdk:
  - openjdk17

brances:
  only:
    - master

# Travis CI서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

notifications:
  email:
    recipients:
      - ehs208@naver.com